# This workflow is triggered for every push and every pull request to the main branch.
# Uses the (latest) container to run the tests and uploads the coverage report to codecov.io.

name: Lint and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:    
  test:
    runs-on: ubuntu-latest
    needs: build
    container: kubricdockerhub/kubruntu:latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install Test Dependencies
        run: pip3 install -r requirements_dev.txt

      - name: Test with pytest
        run: pytest --cov=./ --cov-report=xml

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
